//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_RecursoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cal_Nomina
    {
        public int Id { get; set; }
        public System.DateTime Ano { get; set; }
        public System.DateTime Mes { get; set; }
        public double Monto_Total { get; set; }
    }
}
