//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal_RecursoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Id { get; set; }
        public int Codigo_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Departamento { get; set; }
        public string Cargo { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public double Salario { get; set; }
        public bool Estatus { get; set; }
    }
}
